<?php

/**
 * Implementation of hook_help().
 */
function collapsedocument_help($path, $arg) {
  switch ($path) {
    case 'admin/help#collapsedocument':
      $output = t('<p>JQuery script that automatically collapses document contents into sections under each h2.</p>');
      return $output;
  }
}

/**
* @brief Implementation of hook_init()
*/
function collapsedocument_init() {
  if (arg(0)!='admin') {
    drupal_add_js('document.write("<script src=\"http:\/\/ajax.googleapis.com\/ajax\/libs\/jquery\/1.4.4\/jquery.min.js\"><\/script>");', 'inline');
//    drupal_add_js('var $jq = jQuery.noConflict();debugger;', 'inline');
    drupal_add_js(drupal_get_path('module', 'collapsedocument') . '/collapsedocument.js');
    drupal_add_css(drupal_get_path('module', 'collapsedocument') . '/collapsedocument.css');
  }
}
